version: '3'

services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      TEST_DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }} # Haal de testdatabase-URL op uit GitHub-secret
      ENVIRONMENT: testing # Omgevingsvariabele voor testfase
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "25060:5432"
