version: '3'

services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      DB_PASSWORD: ${{ secrets.DB_URL }}
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${{ secrets.DATABASE_USERNAME }}
      POSTGRES_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      POSTGRES_DB: ${{ secrets.DATABASE_NAME }}
    ports:
      - "25060:25060"

