version: '3'

services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
      DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
      ENVIRONMENT: PRODUCTION
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "25060:5432"
