version: '3'

services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_URL: ${{ secrets.DATABASE_URL }}


