version: '3'

services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "25060:5432"

