version: '3'

services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DBNAME: ${{ secrets.DATABASE_NAME }}
      POSTGRES_USER: ${{ secrets.DATABASE_USERNAME }}
      POSTGRES_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      POSTGRES_HOST: ${{ secrets.DATABASE_HOST }}
      POSTGRES_PORT: ${{ secrets.DATABASE_PORT }}

