version: '3'

services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      TEST_DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
    depends_on:
      - db
      - testdb

  db:
    image: postgres:latest
    environment:
      POSTGRES_DBNAME: ${{ secrets.DATABASE_NAME }}
      POSTGRES_USER: ${{ secrets.DATABASE_USERNAME }}
      POSTGRES_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      POSTGRES_HOST: ${{ secrets.DATABASE_HOST }}
      POSTGRES_PORT: ${{ secrets.DATABASE_PORT }}
    ports:
      - "25060:5432"

  db:
    image: postgres:latest
    environment:
      POSTGRES_DBNAME: ${{ secrets.TEST_DATABASE_NAME }}
      POSTGRES_USER: ${{ secrets.DATABASE_USERNAME }}
      POSTGRES_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      POSTGRES_HOST: ${{ secrets.DATABASE_HOST }}
      POSTGRES_PORT: ${{ secrets.DATABASE_PORT }}
    ports:
      - "25060:5432"
