name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      DB_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}

    steps:
    - uses: actions/checkout@v3
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    - name: Build container image
      run: docker build -t ${{ secrets.REGISTRY_NAME }}/devops_main:$(echo $GITHUB_SHA | head -c7) .
 
    - name: Log in to DigitalOcean Container Registry with short-lived credentials
      run: doctl registry login --expiry-seconds 1200
     
    - name: Push image to DigitalOcean Container Registry
      run: docker push ${{ secrets.REGISTRY_NAME }}/devops_main:$(echo $GITHUB_SHA | head -c7)
    - name: Start Docker container on DigitalOcean Droplet
      run: |
          ssh root@${{ secrets.DROPLET_IP }} << 'EOF'
          docker pull ${{ secrets.REGISTRY_NAME }}/devops_main:$(echo $GITHUB_SHA | head -c7)
          docker run -d -p 80:80 --name devops_container ${{ secrets.REGISTRY_NAME }}/devops_main:$(echo $GITHUB_SHA | head -c7)
          EOF

